//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistrationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigned
    {
        public int AssignID { get; set; }
        public int ComplainID { get; set; }
        public string AssignTo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AssignedBy { get; set; }
    
        public virtual Complain Complain { get; set; }
    }
}
