//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistrationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CommentedBy { get; set; }
        public int ComplainID { get; set; }
    
        public virtual Complain Complain { get; set; }
    }
}
