//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistrationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string CNIC { get; set; }
        public string Cell { get; set; }
        public string Address { get; set; }
        public Nullable<int> LoginID { get; set; }
        public System.DateTime DOB { get; set; }
        public string password { get; set; }

        public virtual Login Login { get; set; }
    }
}
