//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistrationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Allotments = new HashSet<Allotment>();
        }
    
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string RegistrationNumber { get; set; }
        public int DepartmentID { get; set; }
        public string Session { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public int LoginID { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime DOB { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allotment> Allotments { get; set; }
        public virtual Department Department { get; set; }
        public virtual Login Login { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Student Student2 { get; set; }
    }
}
